baseurl = "https://ozgeay.av.tr"
title = "Eva Hukuk & Danışmanlık"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/justice.jpg"
  SEOTitle = "Ozge Ay ve Emine Güldü"
  description = "Eva Avukatlık ve Danışmanlık Web Sitesi"
  keyword = "Özge Ay, Ozge Ay , Sümeyya Emine Güldü, Sumeyya Emine Güldü, Blog, Danışmanlık, Hukuk"
  slogan = "'Adalet ancak hakikatten, saadet de ancak adaletten doğabilir.'   Anatole France"

  image_404 = "img/404-bg.jpg"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Avukat/Lawyer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar1 = "img/ozge-pp.jpeg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar2 = "img/emine-pp.jpeg"

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social1]
  rss            = true 
  email          = "ozgeozdemir57@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/%C3%B6zge-ay-779291204/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  medium        = "https://medium.com/@ozgeay"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"

  [params.social2]
    rss            = true
    email          = "emineguldu@outlook.com"
    #facebook      = "full profile url in facebook"
    #googleplus    = "full profile url in googleplus"
    #twitter       = "full profile url in twitter"
    linkedin       = "https://www.linkedin.com/in/s%C3%BCmeyya-emine-g%C3%BCld%C3%BC-a0028a255/"
    #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
    #instagram     = "full profile url in instagram"
    #github         = "https://github.com/yourgithub"
    #wechat         = "your wechat qr code image"
    #medium        = "https://medium.com/@ozgeay"
    #slack         = "full workspace url in slack"
    #pinterest     = "full profile url in pinterest"
    #reddit        = "full profile url in reddit"
    #gitlab        = "full profile url in gitlab"
    #mastodon      = "full profile url in mastodon"
    #keybase       = "full profile url in keybase"
    #xing          = "https://www.xing.com/profile/yourxingid"
    #git           = "full profile url for git user"
  


  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "BLOG YAZILARIM"
  href =  "/blog/"
  [[params.addtional_menus]]
  title =  "FAALİYET ALANLARIM"
  href =  "/activity/"
  [[params.addtional_menus]]
  title =  "HAKKIMIZDA"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
